baseURL = 'https://elliotdes.github.io/'
languageCode = 'en-us'
theme = "simpleclean"
title = 'elliotdes'

ignoreFiles = ["themes/simpleclean/content/.*"]

[params]
[params.author]
name = 'elliotdes'

[services]
[services.googleAnalytics]
ID = 'G-HNEYSE6EX8'
